# -*- coding: utf-8 -*-
"""user_input.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pBJgjA8C3ziUtKB3wK4CkOIGHQUVb44
"""

name = input("what is your name?")
age = input("what is your age?")
location = input("where do you live?")
print("hello " + name + " you are " + age + " years old and you live in " + location)